stateDiagram-v2
    direction TB
    
    [*] --> ClickAddPOI : Bấm "Thêm mới Địa điểm"
    ClickAddPOI --> InputBasicData : Nhập Tọa độ, Bán kính, Ưu Tiên, Tên
    
    state check_translation <<choice>>
    InputBasicData --> check_translation
    
    check_translation --> PickLanguage : Thêm Bản Dịch
    check_translation --> ValidateData : Không thêm bản dịch nữa
    
    PickLanguage --> InputTranslationData : Nhập Tiêu đề, Kịch bản TTS
    InputTranslationData --> UploadAudioFiles : Upload MP3 (Optional)
    UploadAudioFiles --> check_translation : Vòng lặp thêm bản dịch khác
    
    state check_valid_db <<choice>>
    ValidateData --> check_valid_db
    
    check_valid_db --> ClickAddPOI : Lỗi (Thiếu data, Tọa độ sai)
    check_valid_db --> SaveToDatabase : Dữ liệu hợp lệ
    
    SaveToDatabase --> TriggerMobileUpdate : Gửi cờ thay đổi xuống Mobile App
    TriggerMobileUpdate --> [*]
